# Generated by Django 2.2.5 on 2020-10-16 13:07

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='简述', max_length=128, verbose_name='标题')),
                ('desc', models.CharField(max_length=256, verbose_name='图片描述')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/%Y/%m/%d', verbose_name='图片')),
                ('isshow', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '照片墙',
                'verbose_name_plural': '照片墙',
                'ordering': ['-id'],
            },
        ),
    ]
